apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-project
  labels:
    app: login-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-project
  strategy:
    type: RollingUpdate   
    rollingUpdate:
      maxSurge: 2       
                          
      maxUnavailable: 0   
  template:
    metadata:
      labels:
        app: login-project
    spec:
      containers:
      - image: raam043/kube-project
        name: login-project
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: login-project
 
spec:
  ports:
  - port: 80
    targetPort: 80
  
  selector:
    app: login-project
  type: NodePort
