apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-test
  labels:
    app: eks-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-test
  strategy:
    type: RollingUpdate   
    rollingUpdate:
      maxSurge: 2       
                          
      maxUnavailable: 0   
  template:
    metadata:
      labels:
        app: eks-test
    spec:
      containers:
      - image: raam043/eks-test
        imagePullPolicy: Always
        name: eks-test
        ports:
        - containerPort: 80
        

---
apiVersion: v1
kind: Service
metadata:
  name: eks-test
 
spec:
  ports:
  - port: 80
    targetPort: 80
  
  selector:
    app: eks-test
  type: LoadBalancer
