apiVersion: v1
kind: Pod
metadata:
  name: login-project
  labels:
    app: login-project
spec:
  containers:
  command: "kubectl delete all --all"
  - image: raam043/login-project 
    name: login-project
    ports:
    - containerPort: 80
